sudo: required

services:
    - docker
    
before_install:
    - docker build -t fhsinchy/deno-blog .

script:
    - docker run fhsinchy/deno-blog test --allow-env tests/version.test.ts

# deploy:
#     provider: elasticbeanstalk
#     region: "us-east-2"
#     app: "deno-blog"
#     env: "DenoBlog-env"
#     bucket_name: "elasticbeanstalk-us-east-2-890476563482"
#     bucket_path: "deno-blog"

# on:
#     branch: master

# access_key_id: $AWS_IAM_USER_ID
# secret_access_key:
#     secure: "$AWS_IAM_USER_SECRET"